export const CITIES = [
  "Brussels",
  "Algiers",
  "Bucharest",
  "Brasilia",
  "New Delhi",
  "Warsaw",
  "Athens",
  "Stockholm",
  "Kuala Lumpur",
  "Tokyo",
  "Cairo",
  "Beijing",
  "Berlin",
  "Santiago",
  "Bangkok",
  "Ottawa",
  "Quito",
  "Lahore",
  "Hanoi",
  "Paris",
  "London",
  "Madrid",
  "Rome",
  "Lisbon",
  "Amsterdam",
  "Vienna",
  "Prague",
  "Budapest",
  "Moscow",
  "Oslo",
  "Helsinki",
  "Copenhagen",
  "Dublin",
  "Reykjavik",
  "Washington",
  "Canberra",
  "Wellington",
  "Seoul",
  "Jakarta",
  "Manila",
  "Riyadh",
  "Dubai",
  "Istanbul",
  "Mexico City",
  "Lima",
  "Buenos Aires",
  "Caracas",
  "Bogota",
  "Lagos",
  "Nairobi",
  "Johannesburg",
  "Addis Ababa",
  "Tehran",
  "Baghdad",
  "Damascus",
  "Beirut",
  "Amman",
  "Kuwait City",
  "Doha",
  "Muscat",
  "Islamabad",
  "Kabul",
  "Tashkent",
  "Astana",
  "Bishkek",
  "Ashgabat",
  "Tbilisi",
  "Yerevan",
  "Baku",
  "Riga",
  "Tallinn",
  "Vilnius",
  "Minsk",
  "Kyiv",
  "Chisinau",
  "Belgrade",
  "Sarajevo",
  "Podgorica",
  "Skopje",
  "Sofia",
  "Tirana",
  "Zagreb",
  "Ljubljana",
  "Bratislava",
  "Valletta",
  "Nicosia",
  "Luxembourg",
  "Monaco",
  "San Marino",
  "Andorra la Vella",
  "Vatican City",
  "Bern",
  "Havana",
  "Kingston",
  "Port-au-Prince",
  "Santo Domingo",
  "San Juan",
  "San Salvador",
  "Guatemala City",
  "Tegucigalpa",
  "Managua",
  "San Jose",
  "Panama City",
  "Casablanca",
  "Rabat",
  "Tunis",
  "Tripoli",
  "Bamako",
  "Dakar",
  "Abuja",
  "Accra",
  "Abidjan",
  "Douala",
  "Yaoundé",
  "Brazzaville",
  "Kinshasa",
  "Luanda",
  "Harare",
  "Lusaka",
  "Windhoek",
  "Maputo",
  "Gaborone",
  "Antananarivo",
  "Port Louis",
  "Moroni",
  "Victoria",
  "Malabo",
  "Libreville",
  "Conakry",
  "Freetown",
  "Monrovia",
  "Lome",
  "Cotonou",
  "Ouagadougou",
  "Niamey",
  "Nouakchott",
  "N'Djamena",
  "Bangui",
  "Kigali",
  "Bujumbura",
  "Djibouti",
  "Asmera",
  "Mogadishu",
  "Mbabane",
  "Lobamba",
  "Pretoria",
  "Cape Town",
  "Bloemfontein",
  "Khartoum",
  "Juba",
  "Dodoma",
  "Dar es Salaam",
  "Lilongwe",
  "Maseru",
  "Gaborone",
  "Windhoek",
  "Lusaka",
  "Harare",
  "Maputo",
  "Nairobi",
  "Kampala",
  "Dodoma",
  "Dar es Salaam",
  "Mogadishu",
  "Addis Ababa",
  "Djibouti",
  "Juba",
  "Khartoum",
];

export const TOGGLE_CITY_BTNS = [
  { label: "Now", url: "/" },
  { label: "5 Days", url: "/5Days" },
];

export const WEEK_DAYS = [
  {
    day: "Fri",
    weather: "Clouds",
    temperature: "H:34°C/L:27°C",
    image: "/assets/weather-cloudy.svg",
  },
  {
    day: "Sat",
    weather: "Clouds",
    temperature: "H:34°C/L:27°C",
    image: "/assets/weather-cloudy.svg",
  },
  {
    day: "Sun",
    weather: "Partly Cloudy",
    temperature: "H:38°C/L:31°C",
    image: "/assets/weather-partly-cloudy.svg",
  },
  {
    day: "Mon",
    weather: "Clouds",
    temperature: "H:34°C/L:27°C",
    image: "/assets/weather-cloudy.svg",
  },
  {
    day: "Tue",
    weather: "Clouds",
    temperature: "H:34°C/L:27°C",
    image: "/assets/weather-cloudy.svg",
  },
];

export const UNITS_BTN = ["Imperial", "Metric", "Standard"];
export const UNITS_TIME = ["AM/PM", "24h"];

export const SAVE_ACTION = ["Cancel", "Save"];

export const weatherIconMap: { [key: string]: string } = {
  Clear: "/assets/weather-clear.svg",
  Clouds: "/assets/weather-cloudy.svg",
  Mist: "/assets/weather-fog.svg",
  Smoke: "/assets/weather-fog.svg",
  Haze: "/assets/weather-fog.svg",
  Sand: "/assets/weather-fog.svg",
  Dust: "/assets/weather-fog.svg",
  "Volcanic ash": "/assets/weather-fog.svg",
  Fog: "/assets/weather-fog.svg",
  Squalls: "/assets/weather-windy.svg",
  Tornado: "/assets/weather-windy.svg",
  Rain: "/assets/weather-pouring.svg",
  Snow: "/assets/weather-snowy.svg",
  Sleet: "/assets/weather-snowy-rainy.svg",
  Drizzle: "/assets/weather-lightning-rainy.svg",
  Thunderstorm: "/assets/weather-lightning.svg",
  "Partly Cloudy": "/assets/weather-partly-cloudy.svg",
  Overcast: "/assets/weather-cloudy.svg",
  "Light Rain": "/assets/weather-lightning-rainy.svg",
  "Moderate Rain": "/assets/weather-lightning-rainy.svg",
  "Heavy Rain": "/assets/weather-pouring.svg",
  "Extreme Rain": "/assets/weather-pouring.svg",
  "Freezing Rain": "/assets/weather-snowy.svg",
  "Light Snow": "/assets/weather-snowy.svg",
  "Heavy Snow": "/assets/weather-snowy-heavy.svg",
  "Heavy Snowfall": "/assets/weather-snowy-heavy.svg",
  "Heavy Shower Snow": "/assets/weather-snowy-heavy.svg",
  Night: "/assets/weather-night.svg",
  Sunny: "/assets/weather-sunny.svg",
  Sunset: "/assets/weather-sunset.svg",
  Sunrise: "/assets/weather-sunset.svg",
  Windy: "/assets/weather-windy-variant.svg",
  Hail: "/assets/weather-hail.svg",
};
